### ISSUE TITLE
What creates the `Peek call Hierarchy` menu entry?

### ISSUE THREAD

**Issue by qbrent** [jrieken/demo-callhierarchy#5]
Definitely a request for help; not a real issue; if there is a better forum to ask on then please point me on my way.

Looking through the code of the demo; I can't see what creates the `Peek call Hierarchy` menu entry.

When I comment out the below it no longer appears.

`vscode.languages.registerCallHierarchyProvider('abc', new abcLang.AbcLangHierarchyProvider(abcBrain));`

But; I don't know what that line is triggering in order to add it to the menu.

I imagine the menu entry is coming from: https://github.com/microsoft/vscode/blob/b0dccbcf75fd03ac8cc0fa94da5c552a4f47309d/src/vs/workbench/contrib/callHierarchy/browser/callHierarchy.contribution.ts#L120

Does `registerCallHierarchyProvider` also toggle on a setting to tell the UI to show that entry?

Thanks

**Comment by jrieken** [comment]
> Does registerCallHierarchyProvider also toggle on a setting to tell the UI to show that entry?

Yeah. extension only register "data providers" and that enables/disables the UIs for it. E.g vscode ships with the UI and skeleton for provider doesn't actually know how to compute the data. That's what we leave to extensions. 

> if there is a better forum to ask on then please point me on my way.

Yeah, vscode-doc or vscode-extension-samples is likely the better place...
